const imagePath = {
  aboutImage1: './images/about-image-1.jpg',
  aboutImage2: './images/about-image-2.jpg',
  aboutImage3: './images/about-image-3.jpg',
  aboutImage4: './images/about-image-4.jpg',
  aboutImage5: './images/about-image-5.jpg',
  aboutImage6: './images/about-image-6.jpg',
  aboutImage7: './images/about-image-7.jpg',
  aboutImage8: './images/about-image-8.jpg',
  aboutImage9: './images/about-image-9.jpg',
  commitFairImg: './images/commit-fair.jpg',
  commitLowImpactImg: './images/commit-low-impact.jpg',
  commitOrganicImg: './images/commit-organic.jpg',
  commitRecylingImg: './images/commit-recyling.jpg',
  commitRenewableImg: './images/commit-renewable.jpg',
  featuredProducts1: './images/featured-prod-1.jpg',
  featuredProducts2: './images/featured-prod-2.jpg',
  featuredProducts3: './images/featured-prod-3.jpg',
  featuredProducts4: './images/featured-prod-4.jpg',
  heroImage: './images/hero-image.jpg',
  iconFair: './images/commit-fair-icon.png',
  iconLowImpact: './images/commit-low-impact-icon.png',
  iconOrganic: './images/commit-organic-icon.png',
  iconRecyling: './images/commit-recyling-icon.png',
  iconRenewable: './images/commit-renewable-icon.png',
  logo: './images/logo.png',
  office: './images/office.jpg',
  portrait1: './images/portrait-1.jpg',
  portrait2: './images/portrait-2.jpg',
  portrait3: './images/portrait-3.jpg',
  portrait4: './images/portrait-4.jpg',
  portrait5: './images/portrait-5.jpg',
  portrait6: './images/portrait-6.jpg',
  portrait7: './images/portrait-7.jpg',
  portrait8: './images/portrait-8.jpg',
  review1: './images/review-1.jpg',
  review2: './images/review-2.jpg',
  review3: './images/review-3.jpg',
  review4: './images/review-4.jpg',
  review5: './images/review-5.jpg',
  review6: './images/review-6.jpg',
}

export default imagePath
