const imagePath = {
  aboutImage1: './images/about-image-1.jpg',
  aboutImage2: './images/about-image-2.jpg',
  aboutImage3: './images/about-image-3.jpg',
  aboutImage4: './images/about-image-4.jpg',
  aboutImage5: './images/about-image-5.jpg',
  aboutImage6: './images/about-image-6.jpg',
  aboutImage7: './images/about-image-7.jpg',
  aboutImage8: './images/about-image-8.jpg',
  aboutImage9: './images/about-image-9.jpg',
  commitFair: './images/commit-fair.png',
  commitLowImpact: './images/commit-low-impact.png',
  commitOrganic: './images/commit-organic.png',
  commitRecyling: './images/commit-recyling.png',
  commitRenewable: './images/commit-renewable.png',
  featuredProducts1: './images/featured-prod-1.jpg',
  featuredProducts2: './images/featured-prod-2.jpg',
  featuredProducts3: './images/featured-prod-3.jpg',
  featuredProducts4: './images/featured-prod-4.jpg',
  heroImage: './images/hero-image.jpg',
  logo: './images/logo.png',
  review1: './images/review-1.jpg',
  review2: './images/review-2.jpg',
  review3: './images/review-3.jpg',
  review4: './images/review-4.jpg',
  review5: './images/review-5.jpg',
  review6: './images/review-6.jpg',
}

export default imagePath
